Photo_Contest/Image.MVC/Models/ContestViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Image.MVC.Models
{
    public class ContestViewModel
    {
        public string Title { get; set; }       

        public DateTime PhaseITimeLimit { get; set; }

        public DateTime PhaseIITimeLimit { get; set; }

    }
}

Photo_Contest/Image.MVC/Models/ErrorViewModel.cs
using System;

namespace Image.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Photo_Contest/Image.MVC/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Image.MVC.Models
{
    public class LoginViewModel
    {
		[Required]
		[EmailAddress]
		// [DataType(DataType.EmailAddress)]
		public string Email { get; set; }

		[Required]
		[DataType(DataType.Password)]
		public string Password { get; set; }
	}
}

Photo_Contest/Image.MVC/Models/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Image.MVC.Models
{
    public class RegisterViewModel
    {
		[Required]
		[EmailAddress]
		[Display(Name = "E-mail")]
		public string Email { get; set; }

		//[Required]
		[Display(Name = "Username")]
		[StringLength(maximumLength: 20, MinimumLength = 3, ErrorMessage = "The Username must be between 3 and 20 characters long")]
		public string Username { get; set; }

		//[Required]
		[Display(Name = "First Name")]
		public string FirstName { get; set; }

		//[Required]
		[Display(Name = "Last Name")]
		public string LastName { get; set; }


		[Required]
		[DataType(DataType.Password)]
		[Display(Name = "Password")]
		[StringLength(maximumLength: 20, MinimumLength = 3, ErrorMessage = "The password must be between 3 and 20 characters long")]
		public string Password { get; set; }

		[Required]
		[DataType(DataType.Password)]
		[Display(Name = "Confirm password")]
		[Compare("Password", ErrorMessage = "The password and confirm password fields must match")]
		public string ConfirmPassword { get; set; }

	}
}

Photo_Contest/Image.MVC/Controllers/AccountController.cs
using Image.Data.Models;
using Image.MVC.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Image.MVC.Controllers
{
    public class AccountController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly SignInManager<User> signInManager;

        public AccountController(UserManager<User> userManager, SignInManager<User> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }
        [HttpGet]
        public IActionResult Login()
        {
            var model = new LoginViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await this.signInManager.PasswordSignInAsync(model.Email, model.Password, isPersistent: false, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            return RedirectToAction("Error", "Home");
        }

        [HttpGet]
        public IActionResult Register()
        {
            var model = new RegisterViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new User();
                user.Email = model.Email;
                user.UserName = "username";
               // user.FirstName = model.Email;
               // user.LastName = model.Email;

                var result = await this.userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            return RedirectToAction("Error", "Home");
        }

    }
}

Photo_Contest/Image.MVC/Controllers/ContestController.cs
using Image.Data.Models;
using Image.MVC.Models;
using Image.Service.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Image.MVC.Controllers
{
    public class ContestController : Controller
    {
        private readonly IContestPageServices _contestPageServices;

        public ContestController( IContestPageServices contestPageServices)
        { 
            this._contestPageServices = contestPageServices;
        }
        public IActionResult Index()
        {
            var contests = _contestPageServices.GetAll();
            return this.View(model: contests);
        }

        [HttpGet]  
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(ContestViewModel obj)
        {
            if (ModelState.IsValid)
            {
                var contest = new Contest();
                contest.Title = obj.Title;
                contest.PhaseI = obj.PhaseITimeLimit;
                contest.PhaseII = obj.PhaseIITimeLimit;
                _contestPageServices.Create(contest);
            }
            return View(obj);
        }
    }
}

Photo_Contest/Image.MVC/Controllers/HomeController.cs
using Image.MVC.Models;
using Image.Service.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Image.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IContestPageServices _contestPageServices;

        public HomeController(ILogger<HomeController> logger, IContestPageServices contestPageServices)
        {
            _logger = logger;
            this._contestPageServices = contestPageServices;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Contests()
        {
            var contests = _contestPageServices.GetAll();
            return this.View(model: contests);
        }

      
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Photo_Contest/Image.MVC/Views/Contest/Create.cshtml
@model Image.MVC.Models.ContestViewModel

<form method="post" asp-action="Create">
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Add Category</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Title"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="PhaseITimeLimit"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="PhaseITimeLimit" class="form-control" />
                        <span asp-validation-for="PhaseITimeLimit" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="PhaseIITimeLimit"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="PhaseIITimeLimit" class="form-control" />
                        <span asp-validation-for="PhaseIITimeLimit" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Photo_Contest/Image.MVC/Views/Contest/Index.cshtml
@model IEnumerable<Image.Data.Models.Contest>

@{
    ViewData["Title"] = "Contests";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Contests</h1>

<p>
    <a asp-controller="Contest" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
               
                @Html.DisplayNameFor(model => model.ContestPhase)
                
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContestPhase)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td>
                <button type="button" class="btn btn-info">Attend</button>
            </td>

        </tr>
        }
    </tbody>
</table>

Photo_Contest/Image.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Photo_Contest/Image.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Image.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Image.MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Landing Page</a>
                        </li>                      
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contest" asp-action="Index">Contests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark "   asp-area="" asp-controller="Account" asp-action="Login">Log in</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark "  asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Image.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>